//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: echo.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import SwiftProtobuf


/// Usage: instantiate `Echo_EchoServiceClient`, then call methods of this protocol to make API calls.
public protocol Echo_EchoServiceClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Echo_EchoServiceClientInterceptorFactoryProtocol? { get }

  func echo(
    _ request: Echo_EchoMessage,
    callOptions: CallOptions?
  ) -> UnaryCall<Echo_EchoMessage, Echo_EchoMessage>

  func echoStream(
    callOptions: CallOptions?,
    handler: @escaping (Echo_EchoMessage) -> Void
  ) -> BidirectionalStreamingCall<Echo_EchoMessage, Echo_EchoMessage>
}

extension Echo_EchoServiceClientProtocol {
  public var serviceName: String {
    return "echo.EchoService"
  }

  /// Unary call to Echo
  ///
  /// - Parameters:
  ///   - request: Request to send to Echo.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func echo(
    _ request: Echo_EchoMessage,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Echo_EchoMessage, Echo_EchoMessage> {
    return self.makeUnaryCall(
      path: "/echo.EchoService/Echo",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeEchoInterceptors() ?? []
    )
  }

  /// Bidirectional streaming call to EchoStream
  ///
  /// Callers should use the `send` method on the returned object to send messages
  /// to the server. The caller should send an `.end` after the final message has been sent.
  ///
  /// - Parameters:
  ///   - callOptions: Call options.
  ///   - handler: A closure called when each response is received from the server.
  /// - Returns: A `ClientStreamingCall` with futures for the metadata and status.
  public func echoStream(
    callOptions: CallOptions? = nil,
    handler: @escaping (Echo_EchoMessage) -> Void
  ) -> BidirectionalStreamingCall<Echo_EchoMessage, Echo_EchoMessage> {
    return self.makeBidirectionalStreamingCall(
      path: "/echo.EchoService/EchoStream",
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeEchoStreamInterceptors() ?? [],
      handler: handler
    )
  }
}

public protocol Echo_EchoServiceClientInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when invoking 'echo'.
  func makeEchoInterceptors() -> [ClientInterceptor<Echo_EchoMessage, Echo_EchoMessage>]

  /// - Returns: Interceptors to use when invoking 'echoStream'.
  func makeEchoStreamInterceptors() -> [ClientInterceptor<Echo_EchoMessage, Echo_EchoMessage>]
}

public final class Echo_EchoServiceClient: Echo_EchoServiceClientProtocol {
  public let channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Echo_EchoServiceClientInterceptorFactoryProtocol?

  /// Creates a client for the echo.EchoService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Echo_EchoServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

