//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: sync.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import SwiftProtobuf


/// Usage: instantiate `Sync_SyncServiceClient`, then call methods of this protocol to make API calls.
public protocol Sync_SyncServiceClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Sync_SyncServiceClientInterceptorFactoryProtocol? { get }

  func synchronize(
    callOptions: CallOptions?,
    handler: @escaping (Sync_ServerMessage) -> Void
  ) -> BidirectionalStreamingCall<Sync_ClientMessage, Sync_ServerMessage>
}

extension Sync_SyncServiceClientProtocol {
  public var serviceName: String {
    return "sync.SyncService"
  }

  /// Bidirectional streaming call to Synchronize
  ///
  /// Callers should use the `send` method on the returned object to send messages
  /// to the server. The caller should send an `.end` after the final message has been sent.
  ///
  /// - Parameters:
  ///   - callOptions: Call options.
  ///   - handler: A closure called when each response is received from the server.
  /// - Returns: A `ClientStreamingCall` with futures for the metadata and status.
  public func synchronize(
    callOptions: CallOptions? = nil,
    handler: @escaping (Sync_ServerMessage) -> Void
  ) -> BidirectionalStreamingCall<Sync_ClientMessage, Sync_ServerMessage> {
    return self.makeBidirectionalStreamingCall(
      path: "/sync.SyncService/Synchronize",
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSynchronizeInterceptors() ?? [],
      handler: handler
    )
  }
}

public protocol Sync_SyncServiceClientInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when invoking 'synchronize'.
  func makeSynchronizeInterceptors() -> [ClientInterceptor<Sync_ClientMessage, Sync_ServerMessage>]
}

public final class Sync_SyncServiceClient: Sync_SyncServiceClientProtocol {
  public let channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Sync_SyncServiceClientInterceptorFactoryProtocol?

  /// Creates a client for the sync.SyncService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Sync_SyncServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

